config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  require 'sidekiq-scheduler/web'
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  get '/daily_news', to: 'home#daily_news'
  root 'home#index'
  resources :books
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_categories
  has_many :categories, through: :book_categories
  belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :authenticate_user!
  load_and_authorize_resource 

  # Render list of all {Book}
  def index
    # @books = current_user.books

    # Includes gives all of the books doesnt care if it is assiciated with user or not
    # Uses each resource seprately (2 queries)
    # Includes - include all (preloads in memeory)
    # Can be used to avoid N + 1 problem
    # acts like preload by default
    # Acts like eager_load if you reference the associated tables
    @books = Book.includes(:user).where(user_id: current_user.id)

    # Only give books which have user associated with it (singe query - inner join)
    # Joins - only with matching books and users
    # But it causes N + 1 query problem for association
    # @books = Book.joins(:user).where(user_id: current_user.id)

    # Single query (left outer joins)
    # can reference the other table columns in where condition
    # @books = Book.eager_load(:user).where(user_id: current_user.id)
    # @books = ListBooks.run!
  end

  # Renders a form to create new {Book}
  def new
    @book = CreateBook.new
  end

  # Creates new {Book}
  def create
    @book = CreateBook.run(book_params)
    return redirect_to @book.result, notice: t('books.create.book') if @book.valid?
    render 'new'
  end

  # Renders a form to edit {Book}
  def edit
    @book = find_book!
  end

  # Update {Book}
  def update
    inputs = { book: find_book! }.reverse_merge(params[:book])
    outcome = UpdateBook.run(inputs)
    if outcome.valid?
      redirect_to outcome.result, notice: t('books.update.book')
    else
      @book = outcome
      render(:edit)
    end
  end

  # Displays specific {Book} details
  def show
    @book = find_book!
  end

  # Deletes a {Book}
  def destroy
    DestroyBook.run!(book: find_book!)
    redirect_to books_url, notice: t('books.destroy.book')
  end

  private

  # Finds a {Book} by ID
  def find_book!
    outcome = FindBook.run(params)
    return outcome.result if outcome.valid?
    not_found('exception')
  end
  
  # load only the needed ability file for a specific controller
  def current_ability
    @current_ability ||= BookAbility.new(current_user) 
  end

  # Whitelist parameters which are required
  #
  # @return [ActionController::Parameters]
  def book_params
    params.require(:book).permit(:title, :release_date, :user_id)
  end
end

app/views/books/_form.html.haml
.center_div
  = render 'layouts/errors', obj: @book
  = form_for @book do |f|
    = f.hidden_field :user_id, value: current_user.id
    .row.mb-3
      = f.label :title, class:"col-sm-2 col-form-label"
      .col-sm-4
        = f.text_field :title, required: true, autofocus: true, placeholder: t('.title_placeholder'), class:"form-control"
    .row.mb-3
      = f.label :release_date, class:"col-sm-2 col-form-label"
      .col-sm-4
        = f.date_field :release_date, autofocus: true, required: true, class:"form-control"
    = f.submit t('.save'), class:"btn btn-primary"

app/views/books/edit.html.haml
= render 'form'

app/views/books/index.html.haml
%table.sp.table.table-striped
  %thead
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"}= t('.title_heading')
      %th{:scope => "col"}= t('.release_date_heading')
      %th{:scope => "col"}= t('.actions_heading')
      %th= button_to t('.new'), new_book_path, class:"btn btn-primary", method: :get, style:"float: right;"
  %tbody
    - @books.each.with_index do |book, index|
      %tr
        %th{:scope => "row"}= index + 1
        %td= book.title
        %td= book.release_date
        %td= link_to t('.show'), book_path(book)
        %td= link_to t('.edit'), edit_book_path(book)
        %td= link_to t('.delete'), book_path(book), method: :delete, data: { confirm: t('.confirm') }

app/views/books/new.html.haml
= render 'form'

app/views/books/show.html.haml
.center_div
  .card
    %h5.card-header= @book.title
    .card-body
      %h5.card-title= @book.release_date
  = link_to 'Back', books_path