config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  require 'sidekiq-scheduler/web'
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  get '/daily_news', to: 'home#daily_news'
  root 'home#index'
  resources :books
end

app/views/layouts/_errors.html.haml
- if obj.errors.any?
  .row
    .col-xs-8.col-xs-offset-2
      .panel.panel-danger
        .panel-heading
          %h2.panel-title
            = pluralize(obj.errors.count, "error")
          .panel-body
            %ul
              - obj.errors.full_messages.each do |msg|
                %li= msg

app/views/layouts/_header.html.haml
.header
  %span.login-buttons
    = link_to 'Daily News', daily_news_path, class:"btn btn-primary"
    - unless user_signed_in?
      = link_to 'Log In', new_user_session_path, class:"btn btn-primary"
      = link_to 'Sign Up', new_user_registration_path, class:"btn btn-success"
    - else
      = link_to 'Log out', destroy_user_session_path, method: :delete, class:"btn btn-primary"
  %h2
    %a.navbar-brand{:href => "/"} Deqode Training
  .progress-container
    #myBar.progress-bar

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:align => "center"}
    %br/
    = content_tag :div, msg, class: "alert alert-info"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DeqodeTraining
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    = yield